[package]
name = "artificer"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
inventory = "0.3"
phf = { version = "0.11", features = ["macros"] }
reqwest = { version = "0.13.1", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.48", features = ["full"] }